export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'
export const ADD_PRODUCT = 'ADD_PRODUCT';
